/*  spring.datasource.url=jdbc:postgresql://localhost:5432/game_db?stringtype=unspecified&options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG   */
